[configuration]
default_spacing = 1
space_width = 3

[[glyphs]]
bitmap = """
 X 
X X
XXX
X X
X X
"""
characters = ["A", "a", "А", "а"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X X
XX 
"""
characters = ["B", "b", "В", "в"]

[[glyphs]]
bitmap = """
 XX
X  
X  
X  
 XX
"""
characters = ["C", "c", "С", "с"]

[[glyphs]]
bitmap = """
XX 
X X
X X
X X
XX 
"""
characters = ["D", "d"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X  
XXX
"""
characters = ["E", "e", "Е", "е", "Ё", "ё"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X  
X  
"""
characters = ["F", "f"]

[[glyphs]]
bitmap = """
 XX
X  
X  
X X
 XX
"""
characters = ["G", "g"]

[[glyphs]]
bitmap = """
X X
X X
XXX
X X
X X
"""
characters = ["H", "h", "Н", "н"]

[[glyphs]]
bitmap = """
XXX
 X 
 X 
 X 
XXX
"""
characters = ["I", "i"]

[[glyphs]]
bitmap = """
  X
  X
  X
x X
 X 
"""
characters = ["J", "j"]

[[glyphs]]
bitmap = """
X X
X X
XX 
X X
X X
"""
characters = ["K", "k", "К", "к"]

[[glyphs]]
bitmap = """
X  
X  
X  
X  
XXX
"""
characters = ["L", "l"]

[[glyphs]]
bitmap = """
X   X
XX XX
X X X
X   X
X   X
"""
characters = ["M", "m", "М", "м"]

[[glyphs]]
bitmap = """
X   X
XX  X
X X X
X  XX
X   X
"""
characters = ["N", "n"]

[[glyphs]]
bitmap = """
 X 
X X
X X
X X
 X 
"""
characters = ["O", "o", "О", "о"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X  
X  
"""
characters = ["P", "p", "Р", "р"]

[[glyphs]]
bitmap = """
 X  
X X 
X X 
X X 
 X X
"""
characters = ["Q", "q"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X X
X X
"""
characters = ["R", "r"]

[[glyphs]]
bitmap = """
 XX
X  
 X 
  X
XX 
"""
characters = ["S", "s"]

[[glyphs]]
bitmap = """
XXX
 X 
 X 
 X 
 X 
"""
characters = ["T", "t", "Т", "т"]

[[glyphs]]
bitmap = """
X X
X X
X X
X X
XXX
"""
characters = ["U", "u"]

[[glyphs]]
bitmap = """
X X
X X
X X
 X 
 X 
"""
characters = ["V", "v"]

[[glyphs]]
bitmap = """
X   X
X   X
X X X
X X X
 X X 
"""
characters = ["W", "w"]

[[glyphs]]
bitmap = """
X X
X X
 X 
X X
X X
"""
characters = ["X", "x", "Х", "х"]

[[glyphs]]
bitmap = """
X X
X X
 X 
 X 
 X 
"""
characters = ["Y", "y"]

[[glyphs]]
bitmap = """
XXX
  X
 X 
X  
XXX
"""
characters = ["Z", "z"]

[[glyphs]]
bitmap = """
XXX
X  
XX 
X X
XX 
"""
characters = ["Б", "б"]

[[glyphs]]
bitmap = """
XXX
X  
X  
X  
X  
"""
characters = ["Г", "г"]

[[glyphs]]
bitmap = """
 XXX 
 X X 
 X X 
XXXXX
X   X
"""
characters = ["Д", "д"]

[[glyphs]]
bitmap = """
X X X
X X X
 XXX 
X X X
X X X
"""
characters = ["Ж", "ж"]

[[glyphs]]
bitmap = """
XX 
  X
XX 
  X
XX 
"""
characters = ["З", "з"]

[[glyphs]]
bitmap = """
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["И", "и"]

[[glyphs]]
bitmap = """
X X X
X  XX
X X X
XX  X
X   X
"""
characters = ["Й", "й"]

[[glyphs]]
bitmap = """
  XX
 X X
 X X
 X X
X  X
"""
characters = ["Л", "л"]

[[glyphs]]
bitmap = """
XXX
X X
X X
X X
X X
"""
characters = ["П", "п"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
XX 
"""
characters = ["У", "у"]

[[glyphs]]
bitmap = """
 XXX 
X X X
 XXX 
  X  
  X  
"""
characters = ["Ф", "ф"]

[[glyphs]]
bitmap = """
X X 
X X 
X X 
XXXX
   X
"""
characters = ["Ц", "ц"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
  X
"""
characters = ["Ч", "ч"]

[[glyphs]]
bitmap = """
X X X
X X X
X X X
X X X
XXXXX
"""
characters = ["Ш", "ш"]

[[glyphs]]
bitmap = """
X X X 
X X X 
X X X 
XXXXXX
     X
"""
characters = ["Щ", "щ"]

[[glyphs]]
bitmap = """
XX  
 X  
 XX 
 X X
 XX 
"""
characters = ["Ъ", "ъ"]

[[glyphs]]
bitmap = """
X   X
X   X
XX  X
X X X
XX  X
"""
characters = ["Ы", "ы"]

[[glyphs]]
bitmap = """
X  
X  
XX 
X X
XX 
"""
characters = ["Ь", "ь"]

[[glyphs]]
bitmap = """
XX 
  X
XXX
  X
XX 
"""
characters = ["Э", "э"]

[[glyphs]]
bitmap = """
X  X 
X X X
XXX X
X X X
X  X 
"""
characters = ["Ю", "ю"]

[[glyphs]]
bitmap = """
 XX
X X
 XX
X X
X X
"""
characters = ["Я", "я"]

[[glyphs]]
bitmap = """
XXX
X X
X X
X X
XXX
"""
characters = ["0"]

[[glyphs]]
bitmap = """
  X
 XX
X X
  X
  X
"""
characters = ["1"]

[[glyphs]]
bitmap = """
 X 
X X
  X
 X 
XXX
"""
characters = ["2"]

[[glyphs]]
bitmap = """
XX 
  X
 X 
  X
XX 
"""
characters = ["3"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
  X
"""
characters = ["4"]

[[glyphs]]
bitmap = """
XXX
X  
XX 
  X
XX 
"""
characters = ["5"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X X
XXX
"""
characters = ["6"]

[[glyphs]]
bitmap = """
XXX
  X
 X 
 X 
 X 
"""
characters = ["7"]

[[glyphs]]
bitmap = """
 X 
X X
 X 
X X
 X 
"""
characters = ["8"]

[[glyphs]]
bitmap = """
XXX
X X
XXX
  X
XXX
"""
characters = ["9"]

[[glyphs]]
bitmap = """
   
   
XXX
   
   
"""
characters = ["-"]

[[glyphs]]
bitmap = """
 
X
 
X
 
"""
characters = [":"]

[[glyphs]]
bitmap = """
  X  
 X X 
X   X
XXXXX
X   X
X   X
"""
characters = ["A", "А"]

[[glyphs]]
bitmap = """
     
 XXX 
    X
 XXXX
X   X
 XXXX
"""
characters = ["a", "а"]

[[glyphs]]
bitmap = """
XXXX 
X   X
XXXX 
X   X
X   X
XXXX 
"""
characters = ["B", "В"]

[[glyphs]]
bitmap = """
X    
X    
X    
XXXX 
X   X
XXXX 
"""
characters = ["b"]

[[glyphs]]
bitmap = """
     
XXX  
X  X 
XXXX 
X   X
XXXX 
"""
characters = ["в"]

[[glyphs]]
bitmap = """
 XXX 
X   X
X    
X    
X   X
 XXX 
"""
characters = ["C", "С"]

[[glyphs]]
bitmap = """
     
 XXX 
X   X
X    
X   X
 XXX 
"""
characters = ["c", "с"]

[[glyphs]]
bitmap = """
XXX  
X  X 
X   X
X   X
X  X 
XXX  
"""
characters = ["D"]

[[glyphs]]
bitmap = """
    X
    X
    X
 XXXX
X   X
 XXXX
"""
characters = ["d"]

[[glyphs]]
bitmap = """
XXXXX
X    
XXXX 
X    
X    
XXXXX
"""
characters = ["E", "Е", "Ё"]

[[glyphs]]
bitmap = """
     
 XXX 
X   X
XXXXX
X    
 XXX 
"""
characters = ["e", "е", "ё"]

[[glyphs]]
bitmap = """
XXXXX
X    
XXXX 
X    
X    
X    
"""
characters = ["F"]

[[glyphs]]
bitmap = """
  XX 
 X  X
XXX  
 X   
 X   
 X   
"""
characters = ["f"]

[[glyphs]]
bitmap = """
 XXX 
X   X
X    
X  XX
X   X
 XXX 
"""
characters = ["G"]

[[glyphs]]
bitmap = """
     
 XXXX
X   X
 XXXX
    X
 XXX 
"""
characters = ["g"]

[[glyphs]]
bitmap = """
X   X
X   X
XXXXX
X   X
X   X
X   X
"""
characters = ["H", "Н"]

[[glyphs]]
bitmap = """
X    
X    
X    
XXXX 
X   X
X   X
"""
characters = ["h"]

[[glyphs]]
bitmap = """
     
X   X
X   X
XXXXX
X   X
X   X
"""
characters = ["н"]

[[glyphs]]
bitmap = """
XXXXX
  X  
  X  
  X  
  X  
XXXXX
"""
characters = ["I"]

[[glyphs]]
bitmap = """
  X  
     
 XX  
  X  
  X  
XXXXX
"""
characters = ["i"]

[[glyphs]]
bitmap = """
    X
    X
    X
    X
X   X
 XXX 
"""
characters = ["J"]

[[glyphs]]
bitmap = """
    X
     
   XX
    X
    X
XXXX 
"""
characters = ["j"]

[[glyphs]]
bitmap = """
X   X
X  X 
XXX  
X  X 
X   X
X   X
"""
characters = ["K", "К"]

[[glyphs]]
bitmap = """
X    
X   X
X  X 
XXX  
X  X 
X   X
"""
characters = ["k"]

[[glyphs]]
bitmap = """
     
X   X
X  X 
XXX  
X  X 
X   X
"""
characters = ["к"]

[[glyphs]]
bitmap = """
X    
X    
X    
X    
X    
XXXXX
"""
characters = ["L"]

[[glyphs]]
bitmap = """
X    
X    
X    
X    
 X   
  XXX
"""
characters = ["l"]

[[glyphs]]
bitmap = """
X   X
XX XX
X X X
X X X
X   X
X   X
"""
characters = ["M", "М"]

[[glyphs]]
bitmap = """
     
XX X 
X X X
X X X
X   X
X   X
"""
characters = ["m"]

[[glyphs]]
bitmap = """
     
X   X
XX XX
X X X
X   X
X   X
"""
characters = ["м"]

[[glyphs]]
bitmap = """
X   X
XX  X
X X X
X  XX
X   X
X   X
"""
characters = ["N"]

[[glyphs]]
bitmap = """
     
X XX 
XX  X
X   X
X   X
X   X
"""
characters = ["n"]

[[glyphs]]
bitmap = """
 XXX 
X   X
X   X
X   X
X   X
 XXX 
"""
characters = ["O", "О"]

[[glyphs]]
bitmap = """
     
 XXX 
X   X
X   X
X   X
 XXX 
"""
characters = ["o", "о"]

[[glyphs]]
bitmap = """
XXXX 
X   X
XXXX 
X    
X    
X    
"""
characters = ["P", "Р"]

[[glyphs]]
bitmap = """
     
XXXX 
X   X
XXXX 
X    
X    
"""
characters = ["p", "р"]

[[glyphs]]
bitmap = """
 XXX 
X   X
X   X
X   X
X  X 
 XX X
"""
characters = ["Q"]

[[glyphs]]
bitmap = """
     
 XXXX
X   X
 XXXX
    X
    X
"""
characters = ["q"]

[[glyphs]]
bitmap = """
XXXX 
X   X
X  X 
XXX  
X  X 
X   X
"""
characters = ["R"]

[[glyphs]]
bitmap = """
     
X XX 
XX  X
X    
X    
X    
"""
characters = ["r"]

[[glyphs]]
bitmap = """
 XXX 
X   X
 XX  
   X 
X   X
 XXX 
"""
characters = ["S"]

[[glyphs]]
bitmap = """
     
 XXXX
X    
 XXX 
    X
XXXX 
"""
characters = ["s"]

[[glyphs]]
bitmap = """
XXXXX
  X  
  X  
  X  
  X  
  X  
"""
characters = ["T", "Т"]

[[glyphs]]
bitmap = """
 X   
 X   
XXX  
 X   
 X  X
  XX 
"""
characters = ["t"]

[[glyphs]]
bitmap = """
     
XXXXX
  X  
  X  
  X  
  X  
"""
characters = ["т"]

[[glyphs]]
bitmap = """
X   X
X   X
X   X
X   X
X   X
 XXX 
"""
characters = ["U"]

[[glyphs]]
bitmap = """
     
X   X
X   X
X   X
X  XX
 XX X
"""
characters = ["u"]

[[glyphs]]
bitmap = """
X   X
X   X
X   X
 X X 
 X X 
  X  
"""
characters = ["V"]

[[glyphs]]
bitmap = """
     
X   X
X   X
 X X 
 X X 
  X  
"""
characters = ["v"]

[[glyphs]]
bitmap = """
X   X
X   X
X X X
X X X
X X X
 X X
"""
characters = ["W"]

[[glyphs]]
bitmap = """
     
X   X
X   X
X X X
X X X
 X X
"""
characters = ["w"]

[[glyphs]]
bitmap = """
X   X
 X X 
  X  
  X  
 X X 
X   X
"""
characters = ["X", "Х"]

[[glyphs]]
bitmap = """
     
X   X
 X X 
  X  
 X X 
X   X
"""
characters = ["x", "х"]

[[glyphs]]
bitmap = """
X   X
X   X
 X X 
  X  
  X  
  X  
"""
characters = ["Y"]

[[glyphs]]
bitmap = """
     
X   X
X   X
 XXX 
   X 
XXX  
"""
characters = ["y", "у"]

[[glyphs]]
bitmap = """
XXXXX
   X 
  X  
  X  
 X   
XXXXX
"""
characters = ["Z"]

[[glyphs]]
bitmap = """
     
XXXXX
   X 
  X  
 X   
XXXXX
"""
characters = ["z"]

[[glyphs]]
bitmap = """
XXXXX
X    
XXXX 
X   X
X   X
XXXX 
"""
characters = ["Б"]

[[glyphs]]
bitmap = """
 XXX 
X    
X    
XXXX 
X   X
 XXX 
"""
characters = ["б"]

[[glyphs]]
bitmap = """
XXXXX
X    
X    
X    
X    
X    
"""
characters = ["Г"]

[[glyphs]]
bitmap = """
     
XXXXX
X    
X    
X    
X    
"""
characters = ["г"]

[[glyphs]]
bitmap = """
  X  
 X X 
 X X 
 X X 
XXXXX
X   X
"""
characters = ["Д"]

[[glyphs]]
bitmap = """
     
  X  
 X X 
 X X 
XXXXX
X   X
"""
characters = ["д"]

[[glyphs]]
bitmap = """
X X X
X X X
 XXX 
X X X
X X X
X X X
"""
characters = ["Ж"]

[[glyphs]]
bitmap = """
     
X X X
X X X
 XXX 
X X X
X X X
"""
characters = ["ж"]

[[glyphs]]
bitmap = """
XXXX 
    X
XXXX 
    X
    X
XXXX 
"""
characters = ["З"]

[[glyphs]]
bitmap = """
     
XXXX 
    X
XXXX 
    X
XXXX 
"""
characters = ["з"]

[[glyphs]]
bitmap = """
X   X
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["И"]

[[glyphs]]
bitmap = """
     
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["и"]

[[glyphs]]
bitmap = """
X X X
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["Й"]

[[glyphs]]
bitmap = """
  X  
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["й"]

[[glyphs]]
bitmap = """
  XXX
 X  X
 X  X
 X  X
 X  X
X   X
"""
characters = ["Л"]

[[glyphs]]
bitmap = """
     
  XXX
 X  X
 X  X
 X  X
X   X
"""
characters = ["л"]

[[glyphs]]
bitmap = """
XXXXX
X   X
X   X
X   X
X   X
X   X
"""
characters = ["П"]

[[glyphs]]
bitmap = """
     
XXXXX
X   X
X   X
X   X
X   X
"""
characters = ["п"]

[[glyphs]]
bitmap = """
X   X
X   X
 XXX 
   X 
  X  
XX   
"""
characters = ["У"]

[[glyphs]]
bitmap = """
 XXX 
X X X
X X X
 XXX 
  X  
  X  
"""
characters = ["Ф"]

[[glyphs]]
bitmap = """
     
 XXX 
X X X
 XXX 
  X  
  X  
"""
characters = ["ф"]

[[glyphs]]
bitmap = """
X  X 
X  X 
X  X 
X  X 
XXXXX
    X
"""
characters = ["Ц"]

[[glyphs]]
bitmap = """
     
X  X 
X  X 
X  X 
XXXXX
    X
"""
characters = ["ц"]

[[glyphs]]
bitmap = """
X   X
X   X
 XXXX
    X
    X
    X
"""
characters = ["Ч"]

[[glyphs]]
bitmap = """
     
X   X
X   X
 XXXX
    X
    X
"""
characters = ["ч"]

[[glyphs]]
bitmap = """
X   X
X X X
X X X
X X X
X X X
XXXXX
"""
characters = ["Ш"]

[[glyphs]]
bitmap = """
     
X   X
X X X
X X X
X X X
XXXXX
"""
characters = ["ш"]

[[glyphs]]
bitmap = """
X   X 
X X X 
X X X 
X X X 
XXXXX 
    X
"""
characters = ["Щ"]

[[glyphs]]
bitmap = """
      
X   X 
X X X 
X X X 
XXXXX 
    X
"""
characters = ["щ"]

[[glyphs]]
bitmap = """
XX   
 X   
 X   
 XXX 
 X  X
 XXX 
"""
characters = ["Ъ"]

[[glyphs]]
bitmap = """
     
XX   
 X   
 XXX 
 X  X
 XXX 
"""
characters = ["ъ"]

[[glyphs]]
bitmap = """
X   X
X   X
X   X
XX  X
X X X
XX  X
"""
characters = ["Ы"]

[[glyphs]]
bitmap = """
     
X   X
X   X
XX  X
X X X
XX  X
"""
characters = ["ы"]

[[glyphs]]
bitmap = """
X    
X    
X    
XXXX 
X   X
XXXX 
"""
characters = ["Ь"]

[[glyphs]]
bitmap = """
     
X    
X    
XXXX 
X   X
XXXX 
"""
characters = ["ь"]

[[glyphs]]
bitmap = """
XXXX 
    X
XXXXX
    X
    X
XXXX 
"""
characters = ["Э"]

[[glyphs]]
bitmap = """
     
XXXX 
    X
XXXXX
    X
XXXX 
"""
characters = ["э"]

[[glyphs]]
bitmap = """
X  X 
X X X
XXX X
X X X
X X X
X  X 
"""
characters = ["Ю"]

[[glyphs]]
bitmap = """
     
X  X 
X X X
XXX X
X X X
X  X 
"""
characters = ["ю"]

[[glyphs]]
bitmap = """
 XXXX
X   X
 X  X
  XXX
 X  X
X   X
"""
characters = ["Я"]

[[glyphs]]
bitmap = """
     
 XXXX
X   X
 XXXX
 X  X
X   X
"""
characters = ["я"]

[[glyphs]]
bitmap = """
 XXX 
X  XX
X X X
X X X
XX  X
 XXX 
"""
characters = ["0"]

[[glyphs]]
bitmap = """
  X  
 XX  
X X  
  X  
  X  
XXXXX
"""
characters = ["1"]

[[glyphs]]
bitmap = """
 XXX 
X   X
   X 
 XX  
X    
XXXXX
"""
characters = ["2"]

[[glyphs]]
bitmap = """
XXXX 
    X
 XXX 
    X
    X
XXXX 
"""
characters = ["3"]

[[glyphs]]
bitmap = """
   X 
  XX 
 X X 
XXXXX
   X 
   X 
"""
characters = ["4"]

[[glyphs]]
bitmap = """
XXXXX
X    
XXXX 
    X
    X
XXXX 
"""
characters = ["5"]

[[glyphs]]
bitmap = """
 XXX 
X   X
X    
XXXX 
X   X
 XXX 
"""
characters = ["6"]

[[glyphs]]
bitmap = """
XXXXX
    X
   X 
  X  
  X  
  X  
"""
characters = ["7"]

[[glyphs]]
bitmap = """
 XXX 
X   X
 XXX 
X   X
X   X
 XXX 
"""
characters = ["8"]

[[glyphs]]
bitmap = """
 XXX 
X   X
 XXXX
    X
X   X
 XXX 
"""
characters = ["9"]

[[glyphs]]
bitmap = """
     
     
XXXXX
     
     
     
"""
characters = ["-"]

[[glyphs]]
bitmap = """
 
X
 
 
X
 
"""
characters = [":"]

[[glyphs]]
bitmap = """
 
 
 
 
 
"""
characters = [" "] # thin space, same width as ":"

[[glyphs]]
bitmap = """
 
 
 
 
 
 
"""
characters = [" "] # thin space, same width as ":"

