[configuration]
default_spacing = 1

[[glyphs]]
bitmap = """
 X 
X X
XXX
X X
X X
"""
characters = ["A", "a", "А", "а"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X X
XX 
"""
characters = ["B", "b", "В", "в"]

[[glyphs]]
bitmap = """
 XX
X  
X  
X  
 XX
"""
characters = ["C", "c", "С", "с"]

[[glyphs]]
bitmap = """
XX 
X X
X X
X X
XX 
"""
characters = ["D", "d"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X  
XXX
"""
characters = ["E", "e", "Е", "е", "Ё", "ё"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X  
X  
"""
characters = ["F", "f"]

[[glyphs]]
bitmap = """
 XX
X  
X  
X X
 XX
"""
characters = ["G", "g"]

[[glyphs]]
bitmap = """
X X
X X
XXX
X X
X X
"""
characters = ["H", "h", "Н", "н"]

[[glyphs]]
bitmap = """
XXX
 X 
 X 
 X 
XXX
"""
characters = ["I", "i"]

[[glyphs]]
bitmap = """
  X
  X
  X
x X
 X 
"""
characters = ["J", "j"]

[[glyphs]]
bitmap = """
X X
X X
XX 
X X
X X
"""
characters = ["K", "k", "К", "к"]

[[glyphs]]
bitmap = """
X  
X  
X  
X  
XXX
"""
characters = ["L", "l"]

[[glyphs]]
bitmap = """
X   X
XX XX
X X X
X   X
X   X
"""
characters = ["M", "m", "М", "м"]

[[glyphs]]
bitmap = """
X   X
XX  X
X X X
X  XX
X   X
"""
characters = ["N", "n"]

[[glyphs]]
bitmap = """
 X 
X X
X X
X X
 X 
"""
characters = ["O", "o", "О", "о"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X  
X  
"""
characters = ["P", "p", "Р", "р"]

[[glyphs]]
bitmap = """
 X  
X X 
X X 
X X 
 X X
"""
characters = ["Q", "q"]

[[glyphs]]
bitmap = """
XX 
X X
XX 
X X
X X
"""
characters = ["R", "r"]

[[glyphs]]
bitmap = """
 XX
X  
 X 
  X
XX 
"""
characters = ["S", "s"]

[[glyphs]]
bitmap = """
XXX
 X 
 X 
 X 
 X 
"""
characters = ["T", "T", "Т", "т"]

[[glyphs]]
bitmap = """
X X
X X
X X
X X
XXX
"""
characters = ["U", "u"]

[[glyphs]]
bitmap = """
X X
X X
X X
 X 
 X 
"""
characters = ["V", "v"]

[[glyphs]]
bitmap = """
X   X
X   X
X X X
X X X
 X X 
"""
characters = ["W", "w"]

[[glyphs]]
bitmap = """
X X
X X
 X 
X X
X X
"""
characters = ["X", "x", "Х", "х"]

[[glyphs]]
bitmap = """
X X
X X
 X 
 X 
 X 
"""
characters = ["Y", "y"]

[[glyphs]]
bitmap = """
XXX
  X
 X 
X  
XXX
"""
characters = ["Z", "z"]

[[glyphs]]
bitmap = """
XXX
X  
XX 
X X
XX 
"""
characters = ["Б", "б"]

[[glyphs]]
bitmap = """
XXX
X  
X  
X  
X  
"""
characters = ["Г", "г"]

[[glyphs]]
bitmap = """
 XXX 
 X X 
 X X 
XXXXX
X   X
"""
characters = ["Д", "д"]

[[glyphs]]
bitmap = """
X X X
X X X
 XXX 
X X X
X X X
"""
characters = ["Ж", "ж"]

[[glyphs]]
bitmap = """
XX 
  X
XX 
  X
XX 
"""
characters = ["З", "з"]

[[glyphs]]
bitmap = """
X   X
X  XX
X X X
XX  X
X   X
"""
characters = ["И", "и"]

[[glyphs]]
bitmap = """
X X X
X  XX
X X X
XX  X
X   X
"""
characters = ["Й", "й"]

[[glyphs]]
bitmap = """
  XX
 X X
 X X
 X X
X  X
"""
characters = ["Л", "л"]

[[glyphs]]
bitmap = """
XXX
X X
X X
X X
X X
"""
characters = ["П", "п"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
XX 
"""
characters = ["У", "у"]

[[glyphs]]
bitmap = """
 XXX 
X X X
 XXX 
  X  
  X  
"""
characters = ["Ф", "ф"]

[[glyphs]]
bitmap = """
X X 
X X 
X X 
XXXX
   X
"""
characters = ["Ц", "ц"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
  X
"""
characters = ["Ч", "ч"]

[[glyphs]]
bitmap = """
X X X
X X X
X X X
X X X
XXXXX
"""
characters = ["Ш", "ш"]

[[glyphs]]
bitmap = """
X X X 
X X X 
X X X 
XXXXXX
     X
"""
characters = ["Щ", "щ"]

[[glyphs]]
bitmap = """
XX  
 X  
 XX 
 X X
 XX 
"""
characters = ["Ъ", "ъ"]

[[glyphs]]
bitmap = """
X   X
X   X
XX  X
X X X
XX  X
"""
characters = ["Ы", "ы"]

[[glyphs]]
bitmap = """
X  
X  
XX 
X X
XX 
"""
characters = ["Ь", "ь"]

[[glyphs]]
bitmap = """
XX 
  X
XXX
  X
XX 
"""
characters = ["Э", "э"]

[[glyphs]]
bitmap = """
X  X 
X X X
XXX X
X X X
X  X 
"""
characters = ["Ю", "ю"]

[[glyphs]]
bitmap = """
 XX
X X
 XX
X X
X X
"""
characters = ["Я", "я"]

[[glyphs]]
bitmap = """
XXX
X X
X X
X X
XXX
"""
characters = ["0"]

[[glyphs]]
bitmap = """
  X
 XX
X X
  X
  X
"""
characters = ["1"]

[[glyphs]]
bitmap = """
 X 
X X
  X
 X 
XXX
"""
characters = ["2"]

[[glyphs]]
bitmap = """
XX 
  X
 X 
  X
XX 
"""
characters = ["3"]

[[glyphs]]
bitmap = """
X X
X X
XXX
  X
  X
"""
characters = ["4"]

[[glyphs]]
bitmap = """
XXX
X  
XX 
  X
XX 
"""
characters = ["5"]

[[glyphs]]
bitmap = """
XXX
X  
XXX
X X
XXX
"""
characters = ["6"]

[[glyphs]]
bitmap = """
XXX
  X
 X 
 X 
 X 
"""
characters = ["7"]

[[glyphs]]
bitmap = """
 X 
X X
 X 
X X
 X 
"""
characters = ["8"]

[[glyphs]]
bitmap = """
XXX
X X 
XXX
  X
XXX  
"""
characters = ["9"]

[[glyphs]]
bitmap = """
   
    
XXX
   
     
"""
characters = ["-"]

[[glyphs]]
bitmap = """
   
 X  
   
 X 
     
"""
characters = [":"]
