[configuration]
fps = 2

[palette]
"X" = "#00000000" # shadow of the earth onthe  moon
"-" = "#05195a" # the moon's background
"=" = "#05195a" # start light on the moon (dim)
"#" = "#05195a" # star light on themoon (bright)
"*" = "#fffb00" # star

# [[frames]]
# bitmap = """
#   ----  
#  ------ 
# --------
# --------
# --------
# --------
#  ------ 
#   ----  
# """

# [[frames]]
# bitmap = """
#   XXXX  
#  XXXXX- 
# XXXXXX--
# XXXXX---
# XXXX----
# XXX-----
#  ------ 
#   ----  
# """

# [[frames]]
# bitmap = """
# ------- 
# --------
# --------
# --------
# --------
# ------- 
# ------  
#  ----   
# """

# [[frames]]
# bitmap = """
# XXXXXX- 
# XXXXXX--
# XXXXX---
# XXXXX---
# XXXX----
# XX------
# ------- 
#  -----  
# """

[[frames]]
bitmap = """
      - 
      --
     ---
     ---
    ----
  ------
------- 
 -----  
"""

[[frames]]
bitmap = """
      - 
      --
     ---
     ---
    ----
  ------
------- 
 -----  
"""

[[frames]]
bitmap = """
      = 
   *  =-
     =--
     =--
    =---
  ==----
==----- 
 -----  
"""

[[frames]]
bitmap = """
   *  # 
  *** #=
   * #=-
     #=-
    #=--
  ##=---
##=---- 
 -----  
"""

[[frames]]
bitmap = """
   *  # 
  * * #=
   * #=-
     #=-
    #=--
  ##=---
##=---- 
 -----  
"""

[[frames]]
bitmap = """
      - 
      --
     ---
     ---
    ----
  ------
------- 
 -----  
"""

[[frames]]
bitmap = """
      - 
      --
     ---
     ---
    ----
  ------
------- 
 -----  
"""

[[frames]]
bitmap = """
      = 
      =-
     =--
 *   =--
    =---
  ==----
==----- 
 -----  
"""

[[frames]]
bitmap = """
      # 
      #-
 *   #=-
***  #--
 *  #=--
  ##=---
##==--- 
 =----  
"""

[[frames]]
bitmap = """
      # 
      #-
 *   #=-
* *  #--
 *  #=--
  ##=---
##==--- 
 =----  
"""
