[configuration]
fps = 5.0

[palette]
"-" = "#8a99a6"
"+" = "#6e7d8a"
"=" = "#343b42"

[[frames]]
bitmap = """
        -+-     
        +==     
        +=+     
   -+=   -      
   -==   --     
    --  -+=-    
        -==     
                
"""

[[frames]]
bitmap = """
        -+-     
       -+==     
        ==+     
   -=+   -      
   +==   +-     
    -   -==-    
        -==     
                
"""

[[frames]]
bitmap = """
        -+-     
       -+=+     
       -==+     
   -=+  --      
   +==   ++     
    +   -==-    
        -=+     
                
"""

[[frames]]
bitmap = """
        --      
       -+=+     
       -==+     
   -=-  --      
   +==  -++     
   -+   -==-    
         ++     
                
"""

[[frames]]
bitmap = """
        --      
       -+=+     
       -==+     
   -=-  ++      
   +=+  -++     
   -+   -==     
         +-     
                
"""

[[frames]]
bitmap = """
        --      
       -+=-     
       -==-     
   ++-  ++      
   +=+  -==     
   ++   +==     
         --     
                
"""

[[frames]]
bitmap = """
        --      
       -+=-     
       +==-     
   ++  -+=-     
   +=-  -==     
   ++   -==     
         -      
                
"""

[[frames]]
bitmap = """
                
       -++      
       -==      
   -+   ++      
   +=   -==     
   ++   -=+     
                
                
"""

[[frames]]
bitmap = """
                
       -+-      
       -==      
   --   ++      
   +=   -==     
   --    +-     
                
                
"""

[[frames]]
bitmap = """
                
        --      
       -=+      
   -    --      
   ++    =+     
   -     -      
                
                
"""

[[frames]]
bitmap = """
                
        -       
       -=-      
        --      
   +-    +-     
   -            
                
                
"""

[[frames]]
bitmap = """
                
                
       -+       
        --      
   +     +      
                
                
                
"""

[[frames]]
bitmap = """
                
                
        +       
         -      
   +     -      
                
                
                
"""

[[frames]]
bitmap = """
                
                
        -       
         -      
   -            
                
                
                
"""

[[frames]]
bitmap = """
                
                
                
         -      
                
                
                
                
"""

[[frames]]
bitmap = """
                
                
                
         -      
                
                
                
                
"""

[[frames]]
bitmap = """
                
                
                
                
                
                
                
                
"""

[[frames]]
bitmap = """
                
                
                
     -          
     -          
    -           
                
                
"""

[[frames]]
bitmap = """
                
                
            -   
     -      -   
    --          
    -           
                
                
"""

[[frames]]
bitmap = """
                
                
            -   
     -     --   
    -+          
   -+           
                
                
"""

[[frames]]
bitmap = """
                
                
            -   
    --     -+   
    -+          
   -+-          
    -           
                
"""

[[frames]]
bitmap = """
                
                
           --   
    -      -+   
    ++          
   -=-          
   -+           
                
"""

[[frames]]
bitmap = """
                
                
           --   
    -      -=-  
   -++          
   -=+          
   -+           
                
"""

[[frames]]
bitmap = """
                
                
           -+   
    -      -=-  
   -++      -   
   +=+          
   -=-          
                
"""

[[frames]]
bitmap = """
                
                
           -+-  
    -      -=+  
   -=+      -   
   +=+          
   +=-          
    -           
"""

[[frames]]
bitmap = """
                
                
           -+-  
    -      +==  
   +=+     -+-  
   ===          
   ==+          
    -           
"""

[[frames]]
bitmap = """
                
                
           -+-  
    -      +==  
  -+=+     -=+  
  -===          
   ===          
   -+           
"""

[[frames]]
bitmap = """
                
                
           -+-  
           +==  
  -++-     -=+  
  -===          
   ===          
   ++-          
"""

[[frames]]
bitmap = """
                
                
           -+-  
           +==  
  -++-     -=+  
  -==+          
  -===          
   +=-          
"""

[[frames]]
bitmap = """
                
                
           -+-  
           +==  
  -++      -=+  
  +==+          
  -===          
   +=+          
"""

[[frames]]
bitmap = """
                
                
           -+-  
           -==  
  -+-      -=+  
  +==-          
  +===          
   ==+          
"""

[[frames]]
bitmap = """
                
                
            +-  
           -==  
  -+-      -==  
  +==           
  +==+          
  -==+          
"""

[[frames]]
bitmap = """
                
                
            +-  
           -==- 
   -       -==  
  +==           
  +==+          
  -===          
"""

[[frames]]
bitmap = """
                
                
            --  
           -+=  
            ==  
  -++           
  +==+          
  +==+          
"""

[[frames]]
bitmap = """
                
                
            -   
            +=  
            ++  
  -+-           
  +==-          
  -==+          
"""

[[frames]]
bitmap = """
                
                
                
            -=  
            -+  
   -            
  +=+           
  -+=-          
"""

[[frames]]
bitmap = """
                
                
                
            -+  
            --  
                
  -+-           
  -++-          
"""

[[frames]]
bitmap = """
                
                
                
            -+  
             -  
                
  --            
  --+           
"""

[[frames]]
bitmap = """
                
                
                
             -  
                
                
  -             
  - +           
"""

[[frames]]
bitmap = """
                
                
                
             -  
                
                
                
  - -           
"""

[[frames]]
bitmap = """
                
                
                
                
                
                
                
  -             
"""

[[frames]]
bitmap = """
                
                
                
                
                
                
                
  -             
"""

[[frames]]
bitmap = """
                
                
                
                
                
                
                
                
"""

[[frames]]
bitmap = """
                
            -   
        -   -   
        -       
    -           
                
                
                
"""

[[frames]]
bitmap = """
                
            -   
        -   -   
        -       
    -           
                
                
                
"""

[[frames]]
bitmap = """
                
           --   
        -   -   
        --      
    -           
                
                
                
"""

[[frames]]
bitmap = """
            -   
           -+   
        -   -   
        +-      
   -+           
    -           
                
                
"""

[[frames]]
bitmap = """
           --   
           -+   
        -- --   
        +-      
   -+           
    -           
                
                
"""

[[frames]]
bitmap = """
           --   
           +=   
        -- --   
        ++      
   -=   -       
   -+           
                
                
"""

[[frames]]
bitmap = """
           -+   
          -+=   
        -- --   
    -  -+=      
   -=   --      
   -+           
                
                
"""

[[frames]]
bitmap = """
          -++   
          -==   
        -- --   
   --  -+=      
   +=   +-      
   ++           
                
                
"""

[[frames]]
bitmap = """
          -==   
          +==   
        +- --   
   --  -+=-     
   +=-  ++      
   +=           
                
                
"""

[[frames]]
bitmap = """
          +==   
          +==   
        ++ --   
   +-  -==-     
  -==-  ==      
   ==           
                
                
"""

[[frames]]
bitmap = """
          +==   
          +==   
        +- -    
   +-  -+=-     
  -==   ==      
  -==           
                
                
"""

[[frames]]
bitmap = """
         -+==   
          ==+   
        -- -    
   +-  -+=-     
  -==  -==-     
  -==           
                
                
"""

[[frames]]
bitmap = """
          -++   
          ++-   
        --      
   +-  -+=-     
  -==  -==-     
  -=+           
                
          ---   
"""

[[frames]]
bitmap = """
           --   
          --    
        --      
  -+-  -+=-     
  +==  -==-     
  +=+   --      
          --    
         -++-   
"""

[[frames]]
bitmap = """
                
                
        --      
  -+-   +=-     
  +==   ==-     
  +=+   --      
          --    
         -+=-   
"""

[[frames]]
bitmap = """
                
                
         -      
  -+    +=-     
  +==   ==+     
  +=+   --      
          --    
         +==-   
"""

[[frames]]
bitmap = """
                
                
                
  --    +=-     
  +=+   +=-     
  +=-   --      
          --    
         -==    
"""

[[frames]]
bitmap = """
        ---     
        ---     
        ---     
   ---  -+      
  -+=-  -+-     
  -+--  -+--    
        --+     
          ++    
"""

[[frames]]
bitmap = """
        -+-     
        +++     
        +++     
   -++   -      
   -=+   --     
   ---  -++-    
        -+=     
          --    
"""

[[frames]]
bitmap = """
        -+-     
        +==     
        +=+     
   -+=   -      
   -==   --     
    --  -+=-    
        -==     
                
"""

[[frames]]
bitmap = """
        -+-     
        +==     
        +=+     
   -+=   -      
   -==   --     
    --  -+=-    
        -==     
                
"""
