[configuration]
fps = 2

[palette]
"-" = "#f9c434"
"O" = "#f9aa34"

# [[frames]]
# bitmap = """
#   ----  
#  ------ 
# --------
# --------
# --------
# --------
#  ------ 
#   ----  
# """

[[frames]]
bitmap = """
  ----  
 ------ 
--------
--------
--------
--------
 ------ 
  ----  
"""

[[frames]]
bitmap = """
  ----  
 ------ 
--------
---OO---
---OO---
--------
 ------ 
  ----  
"""

[[frames]]
bitmap = """
  ----  
 ------ 
---OO---
--O--O--
--O--O--
---OO---
 ------ 
  ----  
"""

[[frames]]
bitmap = """
  ----  
 --OO-- 
--O--O--
-O----O-
-O----O-
--O--O--
 --OO-- 
  ----  
"""

[[frames]]
bitmap = """
  OOOO  
 O----O 
O------O
O------O
O------O
O------O
 O----O 
  OOOO  
"""
