[configuration]
fps = 5

[palette]
"|" = "#f0cb0d"
"!" = "#ffffff"
"O" = "#9bb8cc"
"X" = "#02005b"
"&" = "#b1b0ff"

# [[frames]]
# bitmap = """
#        XX     
#    XX XOOX    
#   XOOXOOOOXX  
#  XOOOOOOOOOOX 
#   XXXXXXXXXX  
#               
#               
#               
# """

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
    &         
              
              
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
         |    
     &        
              
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      &  |    
        |     
     &        
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
         |    
      & |     
         |    
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
  &      !    
        !     
      &  !    
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
         |    
   &    |     
         |    
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      &  !    
        !     
    &    !    
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
              
       &      
              
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      |   &   
              
       &      
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      |       
      |    &  
              
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      | &     
      |       
     |      & 
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      !       
      !  &    
     !        
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   &  |       
      |       
     |   &    
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
      !       
    & !       
     !        
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
         &    
              
     &        
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   |          
          &   
              
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   |  &       
    |         
           &  
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   |          
    |  &      
    |         
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   !       &  
    !         
    !   &     
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   |          
    |       & 
    |         
"""

[[frames]]
bitmap = """
       XX     
   XX XOOX    
  XOOXOOOOXX  
 XOOOOOOOOOOX 
  XXXXXXXXXX  
   !          
    !         
    !        &
"""
